name: PR and Test

on:
  push:
    branches:
      - Ernest/quill_design_poc

jobs:
  generate_dart_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Command For Generating Dart
        run: npm run build

      - name: Upload Generated Dart Artifacts 
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: dist/quill-tailwind/mobile_theme 

          
  create_pr:
    needs: generate_dart_files
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          repository: ernest-deriv/flutter-deriv-packages 
          ssh-key: ${{ secrets.SSH_PACKAGES }}
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Run ls
        run: ls   
      - name: Copy generated dart files to deriv_theme   
        run: mv mobile_dark_colors.dart mobile_light_colors.dart packages/deriv_theme/

      - name: Setup Git User
        uses: fregante/setup-git-user@77c1b5542f14ab6db4b8462d6857e31deb988b09

      - name: run git add and commit
        run: |
            git add .
            git commit -m 'feat: auto generate files'


      - name: Create Pull Request on updated quill tokens.
        uses: peter-evans/create-pull-request@76c6f5c20e2111bfee3cd30fae52a25e410f5efc
        with:
          token: ${{ secrets.PAT }}
          title: "feat(deriv_theme): automated_update_by_quill"
          base: dev       


     